########################################################

spring.velocity.resourceLoaderPath=classpath:/templates/
spring.velocity.prefix=
spring.velocity.suffix=.vm
spring.velocity.cache=false
spring.velocity.check-template-location=true
spring.velocity.content-type=text/html
spring.velocity.charset=UTF-8
spring.velocity.properties.input.encoding=UTF-8
spring.velocity.properties.output.encoding=UTF-8

#########################################################

default.date.format = yyyy-MM-dd HH:mm:ss
default.path.folder.temp = /sigeadn/temp/
default.path.folder.image = /sigeadn/images/
default.language = fr

eadn.sig.jwtSecret=ENC(WF4RyHiJ4lb/lAzAUQEK2g==)
eadn.sig.jwtRefreshExpirationMs=36000000
eadn.sig.jwtExpirationMs=18000000
eadn.sig.server= https://sig.mjeunesse.gov.dz/api/v1.0
eadn.sig.front.server = https://sig.mjeunesse.gov.dz

redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PASSWORD}
redis.timeout= 60

geoserver.wms.url = https://sig.mjeunesse.gov.dz/geoserver/limite_admin/wms
geoserver.wfs.url = https://sig.mjeunesse.gov.dz/geoserver/limite_admin/wfs
geoserver.rest.url = https://sig.mjeunesse.gov.dz/geoserver/rest
geoserver.rest.user = geo_admin
geoserver.rest.userGuest = guest
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
geoserver.rest.password=${GEOSERVER_REST_PASSWORD}
geoserver.rest.guestRole=GUEST
geoserver.workspace = limite_admin
geoserver.datastore = database

eadn.sig.domaines_autorises=https://sig.mjeunesse.gov.dz
