/**
 * 
 */
package dz.eadn.sig.model;

/**
 * @author LAMOUR AMEUR
 *
 */
public enum Operation {
	CREATION, MODIFICATION, SUPPRISSION, PARTAGE, DEPARTAGE, ATTACHEEMENT, DETACHEMENT, ARCHIVAGE, DESARCHIVAGE,
	CHANGEMENT_PRIVACY, AFFECTATION, CHANGEMENT_STYLE, RENITIALISATION_MOT_PASSE, AJOUTER_UTILISATEUR_DANS_GROUPE,
	SUPPRIMER_UTILISATEUR_DANS_GROUPE, AJOUTER_PERMISSION_DANS_GROUPE, SUPPRIMER_PERMISSION_DANS_GROUPE;
}
